name: Build for Plesk

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy build to deploy branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          mkdir deploy-temp
          cp -r dist/* deploy-temp/

          git fetch origin
          git checkout deploy || git checkout -b deploy

          git rm -rf .
          cp -r deploy-temp/* .

          git add .
          git commit -m "deploy build"
          git push origin deploy --force
